export const projectsData = [
    {
        id: 1,
        name: 'Project Alpha',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        status: 'Active',
        startDate: '2023-01-10',
        endDate: '2023-05-30',
        manager: 'Alice Johnson',
    },
    {
        id: 2,
        name: 'Project Beta',
        description: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        status: 'Completed',
        startDate: '2023-02-15',
        endDate: '2023-04-25',
        manager: 'Bob Smith',
    },
    {
        id: 3,
        name: 'Project Gamma',
        description: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.',
        status: 'On Hold',
        startDate: '2023-03-05',
        endDate: '2023-06-20',
        manager: 'Charlie Davis',
    },
    {
        id: 4,
        name: 'Project Manna',
        description: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.',
        status: 'On Hold',
        startDate: '2023-04-05',
        endDate: '2023-06-20',
        manager: 'Charlie Chaplin',
    },
    {
        id: 5,
        name: 'Project delta',
        description: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.',
        status: 'On Hold',
        startDate: '2023-05-06',
        endDate: '2023-07-20',
        manager: 'Gomez Leroy',
    },
    {
        id: 6,
        name: 'Project Virgo',
        description: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.',
        status: 'On Hold',
        startDate: '2023-06-05',
        endDate: '2023-08-20',
        manager: 'Begworth Edgar',
    },
    {
        id: 7,
        name: 'Project Gemini',
        description: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.',
        status: 'On Hold',
        startDate: '2023-06-25',
        endDate: '2023-08-20',
        manager: 'Leo Leandro',
    },
    {
        id: 8,
        name: 'Project Pisces',
        description: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.',
        status: 'On Hold',
        startDate: '2023-07-10',
        endDate: '2023-08-30',
        manager: 'Charlie Davis',
    },
    {
        id: 9,
        name: 'Project Sagitarius',
        description: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        status: 'On Hold',
        startDate: '2023-02-15',
        endDate: '2023-04-25',
        manager: 'Bob Smith',
    },

  // Add more project objects as needed
];
